# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jsonParser' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'TZImagePickerController', '~> 2.0.1'
    pod 'Masonry', '~> 1.1.0'
    pod 'YYWebImage', '~> 1.0.5'
  # Pods for jsonParser

  target 'jsonParserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'jsonParserUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
